name: mongo-sharding

services:
  configSrv:
    container_name: configSrv
    image: mongo:latest
    restart: always
    volumes:
      - config_data_container:/data/db
    command: [ "--configsvr", "--replSet", "config_server", "--bind_ip_all" ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1:
    container_name: shard1
    image: mongo:latest
    restart: always
    volumes:
      - shard1_data_container:/data/db
    command: [ "--shardsvr", "--replSet", "shard1", "--bind_ip_all" ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2:
    container_name: shard2
    image: mongo:latest
    restart: always
    volumes:
      - shard2_data_container:/data/db
    command: [ "--shardsvr", "--replSet", "shard2", "--bind_ip_all" ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  mongos:
    container_name: mongos
    image: mongo:latest
    restart: always
    depends_on:
      - configSrv
      - shard1
      - shard2
    command: [ "mongos", "--configdb", "config_server/configSrv", "--bind_ip_all" ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  pymongo_api:
    container_name: pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      - mongos
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: "mongodb://mongos"
      MONGODB_DATABASE_NAME: "somedb"

volumes:
  config_data_container:
  shard1_data_container:
  shard2_data_container:
